apiVersion: hydra.ory.sh/v1alpha2
kind: OAuth2Client
metadata:
  name: my-oauth2-client
  namespace: default
spec:
  grantTypes:
    - client_credentials
    - implicit
    - authorization_code
    - refresh_token
  responseTypes:
    - id_token
    - code
    - token
  redirectUris:
    - https://client/account
    - http://localhost:8080
  scope: "read write"
  secretName: my-secret-123
