apiVersion: hydra.ory.sh/v1alpha3
kind: OAuth2Client
metadata:
  name: my-oauth2-client
  namespace: default
spec:
  grantTypes:
    - client_credentials
    - implicit
    - authorization_code
    - refresh_token
  responseTypes:
    - id_token
    - code
    - token
  redirectUris:
    - https://client/account
    - http://localhost:8080
  scope: "read write"
  secretName: my-secret-123
  # these are optional
  redirectUris:
    - https://client/account
    - http://localhost:8080
  hydraAdmin:
    # if hydraAdmin is specified, all of these fields are requried,
    # but they can be empty/0
    url: http://hydra-admin.namespace.cluster.domain
    port: 4445
    endpoint: /clients
    forwardedProto: https
  
