name: Docker Image Scan
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build images
        shell: bash
        run: |
          pwd
          ls -al
          cat ./hack/boilerplate.go.txt
          make docker-build-notest
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: controller:latest
          fail-build: true
          severity-cutoff: high
